name: its_aa_pn_2025_cross_platform
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  collection: ^1.19.1
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  freezed_annotation: ^3.1.0
  go_router: ^16.3.0
  json_annotation: ^4.9.0
  reactive_forms: ^18.1.1
  retrofit: ^4.9.1
  riverpod_annotation: ^3.0.3
  riverpod_swiss_knife: ^0.0.4+1
  shimmer: ^3.0.0
  talker_dio_logger: ^5.1.0
  talker_flutter: ^5.1.0
  talker_riverpod_logger: ^5.1.0
  url_launcher: ^6.3.2

dev_dependencies:
  build_runner: ^2.10.3
  custom_lint: ^0.8.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  retrofit_generator: ^10.2.0
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
